/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Alejandro Padilla
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EditEmp = new javax.swing.JButton();
        RepAsis = new javax.swing.JButton();
        ConfSeg = new javax.swing.JButton();
        ComRegis = new javax.swing.JButton();
        SalBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditEmp.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        EditEmp.setText("Edicion y creacion de perfiles");
        EditEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmpActionPerformed(evt);
            }
        });
        jPanel1.add(EditEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 30));

        RepAsis.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RepAsis.setText("Registro de Asistencia");
        jPanel1.add(RepAsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 30));

        ConfSeg.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ConfSeg.setText("Configuracion seguridad");
        ConfSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfSegActionPerformed(evt);
            }
        });
        jPanel1.add(ConfSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, 30));

        ComRegis.setBackground(new java.awt.Color(255, 102, 0));
        ComRegis.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        ComRegis.setText("Comenzar registro de asistencia");
        jPanel1.add(ComRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 290, 70));

        SalBut.setBackground(new java.awt.Color(255, 102, 0));
        SalBut.setText("X");
        SalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalButActionPerformed(evt);
            }
        });
        jPanel1.add(SalBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmpActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormPrincipal EditEmple = new FormPrincipal();
                EditEmple.setVisible(true);
                EditEmple.setLocationRelativeTo(null);
                dispose();
                
            }
        });
    }//GEN-LAST:event_EditEmpActionPerformed

    private void ConfSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfSegActionPerformed
        Seguridad seg = new Seguridad();
        seg.setVisible(true);
        seg.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_ConfSegActionPerformed

    private void SalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalButActionPerformed
        Formularios.LogIn Inicio = new Formularios.LogIn();
        Inicio.setVisible(true);
        Inicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_SalButActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComRegis;
    private javax.swing.JButton ConfSeg;
    private javax.swing.JButton EditEmp;
    private javax.swing.JButton RepAsis;
    private javax.swing.JButton SalBut;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
