/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Alejandro Padilla
 */
public class Seguridad extends javax.swing.JFrame {

    /**
     * Creates new form Seguridad
     */
    public Seguridad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameUser = new javax.swing.JLabel();
        EstContra = new javax.swing.JLabel();
        ConfContra = new javax.swing.JLabel();
        Usertxt = new javax.swing.JTextField();
        Passtxt1 = new javax.swing.JPasswordField();
        Passtxt2 = new javax.swing.JPasswordField();
        ButConf = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameUser.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        NameUser.setText("Nombre del usuario");
        jPanel1.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, -1));

        EstContra.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        EstContra.setText("Establecer contraseña");
        jPanel1.add(EstContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, -1));

        ConfContra.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ConfContra.setText("Confirmar contraseña");
        jPanel1.add(ConfContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, -1));

        Usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsertxtActionPerformed(evt);
            }
        });
        jPanel1.add(Usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 300, 20));
        jPanel1.add(Passtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 238, 300, -1));
        jPanel1.add(Passtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 312, 300, 20));

        ButConf.setBackground(new java.awt.Color(255, 102, 0));
        ButConf.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ButConf.setText("Confirmar cambios");
        jPanel1.add(ButConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 390, 300, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConfSeguridad.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -5, 890, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsertxtActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButConf;
    private javax.swing.JLabel ConfContra;
    private javax.swing.JLabel EstContra;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPasswordField Passtxt1;
    private javax.swing.JPasswordField Passtxt2;
    private javax.swing.JTextField Usertxt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
