
package Ventanas;


public class MenuBien extends javax.swing.JFrame {

    public MenuBien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotSalir = new javax.swing.JButton();
        BotCreaPrfil = new javax.swing.JButton();
        BotADminPerf = new javax.swing.JButton();
        BotAlerta = new javax.swing.JButton();
        BotHistorial = new javax.swing.JButton();
        BotSeguridad = new javax.swing.JButton();
        BotRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotSalir.setBackground(new java.awt.Color(255, 255, 255));
        BotSalir.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        BotSalir.setForeground(new java.awt.Color(0, 0, 0));
        BotSalir.setBorder(null);
        BotSalir.setBorderPainted(false);
        BotSalir.setContentAreaFilled(false);
        BotSalir.setLabel("");
        BotSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BotSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 40, 60));

        BotCreaPrfil.setBackground(new java.awt.Color(255, 255, 255));
        BotCreaPrfil.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        BotCreaPrfil.setForeground(new java.awt.Color(0, 0, 0));
        BotCreaPrfil.setText("Creacion de perfiles");
        BotCreaPrfil.setBorderPainted(false);
        BotCreaPrfil.setContentAreaFilled(false);
        BotCreaPrfil.setFocusPainted(false);
        jPanel1.add(BotCreaPrfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 230, 50));

        BotADminPerf.setBackground(new java.awt.Color(255, 255, 255));
        BotADminPerf.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        BotADminPerf.setForeground(new java.awt.Color(0, 0, 0));
        BotADminPerf.setText("Administracion de perfiles");
        BotADminPerf.setBorderPainted(false);
        BotADminPerf.setContentAreaFilled(false);
        BotADminPerf.setFocusPainted(false);
        jPanel1.add(BotADminPerf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, 230, 50));

        BotAlerta.setBackground(new java.awt.Color(255, 255, 255));
        BotAlerta.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        BotAlerta.setForeground(new java.awt.Color(0, 0, 0));
        BotAlerta.setText("Alertas de inasistencia");
        BotAlerta.setBorder(null);
        BotAlerta.setBorderPainted(false);
        BotAlerta.setContentAreaFilled(false);
        jPanel1.add(BotAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 238, 230, 50));

        BotHistorial.setBackground(new java.awt.Color(255, 255, 255));
        BotHistorial.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        BotHistorial.setForeground(new java.awt.Color(0, 0, 0));
        BotHistorial.setText("Historial de asistencia");
        BotHistorial.setBorder(null);
        BotHistorial.setBorderPainted(false);
        jPanel1.add(BotHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 50));

        BotSeguridad.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        BotSeguridad.setForeground(new java.awt.Color(0, 0, 0));
        BotSeguridad.setText("Configuracion seguridad");
        BotSeguridad.setBorder(null);
        BotSeguridad.setBorderPainted(false);
        BotSeguridad.setContentAreaFilled(false);
        BotSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(BotSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 40));

        BotRegistro.setBackground(new java.awt.Color(255, 109, 12));
        BotRegistro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        BotRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BotRegistro.setText("Comenzar registro de asistencia");
        BotRegistro.setBorder(null);
        BotRegistro.setBorderPainted(false);
        BotRegistro.setContentAreaFilled(false);
        jPanel1.add(BotRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 190, 320, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuPrincipal.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSalirActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_BotSalirActionPerformed

    private void BotSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSeguridadActionPerformed
        Seguridad1 clave = new Seguridad1();
        clave.setVisible(true);
        clave.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_BotSeguridadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotADminPerf;
    private javax.swing.JButton BotAlerta;
    private javax.swing.JButton BotCreaPrfil;
    private javax.swing.JButton BotHistorial;
    private javax.swing.JButton BotRegistro;
    private javax.swing.JButton BotSalir;
    private javax.swing.JButton BotSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
