/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
/**
 *
 * @author Andrés
 */
public class Menu_opciones extends javax.swing.JFrame {

    /**
     * Creates new form Menu_opciones
     */
    public Menu_opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconimage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo_poo.jpg"));
        return retValue;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_salida = new javax.swing.JButton();
        jButton_salida1 = new javax.swing.JButton();
        jLabel_opciones = new javax.swing.JLabel();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_salida.setBackground(new java.awt.Color(255, 17, 17));
        jButton_salida.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salida.setText("X");
        jButton_salida.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 30));

        jButton_salida1.setBackground(new java.awt.Color(153, 153, 153));
        jButton_salida1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salida1.setText("-");
        jButton_salida1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_salida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salida1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 30));

        jLabel_opciones.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_opciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_opciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/R.jpg"))); // NOI18N
        getContentPane().add(jLabel_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 400));

        jLabel_usuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1155017.jpg"))); // NOI18N
        getContentPane().add(jLabel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 200));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1155032.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 540, 600));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salidaActionPerformed

    private void jButton_salida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salida1ActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton_salida1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_salida;
    private javax.swing.JButton jButton_salida1;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_opciones;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
