/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author Alejandro Padilla
 */
public class EditPerfil extends javax.swing.JFrame {

    /**
     * Creates new form EditPerfil
     */
    public EditPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        EstContra = new javax.swing.JLabel();
        ConfContra = new javax.swing.JLabel();
        ButCrearUser = new javax.swing.JButton();
        TxtUser = new javax.swing.JTextField();
        TxtEstCon = new javax.swing.JPasswordField();
        TxtConfpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        Usuario.setText("Escriba un nuevo usuario");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 190, 20));

        EstContra.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        EstContra.setText("Establezca una contraseña");
        jPanel1.add(EstContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        ConfContra.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        ConfContra.setText("Confirmar contraseña");
        jPanel1.add(ConfContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 170, 20));

        ButCrearUser.setBackground(new java.awt.Color(255, 102, 0));
        ButCrearUser.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        ButCrearUser.setText("Crear usuario");
        jPanel1.add(ButCrearUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 393, 300, -1));
        jPanel1.add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 310, 20));

        TxtEstCon.setText("jPasswordField1");
        jPanel1.add(TxtEstCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 300, -1));

        TxtConfpassword.setText("jPasswordField2");
        jPanel1.add(TxtConfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 443, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConfSeguridad.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Seguridad1 seguri = new Seguridad1();
        seguri.setVisible(true);
        seguri.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCrearUser;
    private javax.swing.JLabel ConfContra;
    private javax.swing.JLabel EstContra;
    private javax.swing.JPasswordField TxtConfpassword;
    private javax.swing.JPasswordField TxtEstCon;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
